# Configuración del puerto del servidor
server.port=8080

# Usar H2 temporalmente para que tu proyecto corra sin errores de driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Configuración de JPA / Hibernate para autogenerar las tablas según tus modelos
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola de H2 habilitada (puedes verla en http://localhost:8080/h2-console)
spring.h2.console.enabled=true